[package]
name = "openspace-app"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { workspace = true }
tracing = { workspace = true }
openspace-theme = { path = "../openspace-theme" }
openspace-welcome = { path = "../openspace-welcome" }
openspace-home = { path = "../openspace-home" }

[dev-dependencies]
toml = "0.8"

[[bin]]
name = "openspace"
path = "src/main.rs"
